-- =====================================================================
-- CivicAI - Master Database Schema DDL for Supabase (PostgreSQL)
-- Copy and paste this entire code directly into your Supabase SQL Editor
-- =====================================================================

-- 1. DEPARTMENTS TABLE
CREATE TABLE IF NOT EXISTS departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. OFFICERS TABLE
CREATE TABLE IF NOT EXISTS officers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    mobile TEXT NOT NULL,
    email TEXT DEFAULT 'officer@civicai.gov.in',
    department_id BIGINT REFERENCES departments(id) ON DELETE CASCADE,
    village TEXT NOT NULL,
    mandal TEXT NOT NULL,
    district TEXT DEFAULT 'Chittoor',
    pincode TEXT DEFAULT '517425',
    state TEXT DEFAULT 'Andhra Pradesh',
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    is_first_login BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    CONSTRAINT unique_officer_per_dept_village UNIQUE (village, mandal, department_id)
);

-- 3. COMPLAINTS TABLE
CREATE TABLE IF NOT EXISTS complaints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_id BIGINT UNIQUE NOT NULL,
    citizen_mobile TEXT NOT NULL,
    original_note TEXT NOT NULL,
    detected_language TEXT DEFAULT 'Telugu',
    latitude NUMERIC(10, 8) NOT NULL,
    longitude NUMERIC(11, 8) NOT NULL,
    state TEXT DEFAULT 'Andhra Pradesh',
    district TEXT DEFAULT 'Chittoor',
    mandal TEXT NOT NULL,
    village TEXT NOT NULL,
    category_id BIGINT REFERENCES departments(id) ON DELETE SET NULL,
    severity TEXT CHECK (severity IN ('EMERGENCY', 'MODERATE', 'MILD')),
    ai_summary TEXT,
    pdf_path TEXT,
    status TEXT CHECK (status IN ('PENDING', 'DISPATCHED', 'ONGOING', 'RESOLVED', 'OVERDUE')) DEFAULT 'PENDING',
    accepted_at TIMESTAMP WITH TIME ZONE,
    deadline_at TIMESTAMP WITH TIME ZONE,
    resolved_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. COMPLAINT PROGRESS UPDATES TABLE (OFFICER TO CITIZEN MULTILINGUAL UPDATES)
CREATE TABLE IF NOT EXISTS complaint_updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complaint_id BIGINT REFERENCES complaints(id) ON DELETE CASCADE,
    officer_id BIGINT REFERENCES officers(id) ON DELETE SET NULL,
    original_update TEXT NOT NULL,
    translated_update TEXT NOT NULL,
    target_language TEXT DEFAULT 'Telugu',
    status_change TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 5. ACTIVITY AUDIT LOGS TABLE
CREATE TABLE IF NOT EXISTS activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type TEXT NOT NULL,
    description TEXT NOT NULL,
    actor_role TEXT CHECK (actor_role IN ('CITIZEN', 'OFFICER', 'ADMIN', 'SYSTEM')) DEFAULT 'SYSTEM',
    actor_id TEXT,
    complaint_id BIGINT REFERENCES complaints(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 6. NOTIFICATIONS TRACKING TABLE
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complaint_id BIGINT REFERENCES complaints(id) ON DELETE CASCADE,
    tracking_id BIGINT NOT NULL,
    recipient_mobile TEXT NOT NULL,
    channel TEXT CHECK (channel IN ('WhatsApp', 'SMS', 'Portal')) DEFAULT 'WhatsApp',
    language TEXT DEFAULT 'Telugu',
    message_text TEXT NOT NULL,
    status TEXT CHECK (status IN ('Sent', 'Pending', 'Failed')) DEFAULT 'Sent',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- =====================================================================
-- DISABLE ROW LEVEL SECURITY FOR UNRESTRICTED HACKATHON ACCESS
-- =====================================================================
ALTER TABLE departments DISABLE ROW LEVEL SECURITY;
ALTER TABLE officers DISABLE ROW LEVEL SECURITY;
ALTER TABLE complaints DISABLE ROW LEVEL SECURITY;
ALTER TABLE complaint_updates DISABLE ROW LEVEL SECURITY;
ALTER TABLE activity_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;

-- =====================================================================
-- SEED DEFAULT DEPARTMENTS
-- =====================================================================
INSERT INTO departments (name) VALUES 
('Water Supply'), 
('Electricity Board'), 
('Roads & Infrastructure'), 
('Sanitation & Waste Management'), 
('Drainage Management')
ON CONFLICT (name) DO NOTHING;

-- =====================================================================
-- SEED DEFAULT DEMO OFFICERS
-- =====================================================================
INSERT INTO officers (name, mobile, email, department_id, village, mandal, district, pincode, state, username, password, is_first_login)
VALUES 
('Ramesh Kumar', '9876543210', 'ramesh.water@civicai.gov.in', 1, 'Kuppam', 'Kuppam', 'Chittoor', '517425', 'Andhra Pradesh', 'officer1', 'pass123', true),
('Srinivas Rao', '9123456789', 'srinivas.power@civicai.gov.in', 2, 'Kuppam', 'Kuppam', 'Chittoor', '517425', 'Andhra Pradesh', 'officer2', 'pass123', true)
ON CONFLICT (username) DO NOTHING;

